# Домашняя работа №1

Создайте случайный FloatTensor размера 3x4x5 <br>
Выведите его форму (shape)<br>
Приведите его к форме 6х10<br>
Создайте случайный IntTensor размера 10<br>
Умножьте созданный FloatTensor на созданный IntTensor поэлементно<br>
Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти<br>
Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)<br>
Создайте единичный тензор размера 5x6<br>
Переведите его в формат numpy<br>

In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
a=torch.rand(60)
q=a.reshape(3,4,5)
print(q)
print(q.size())

tensor([[[0.1353, 0.1042, 0.2091, 0.9364, 0.3208],
         [0.1104, 0.7617, 0.8838, 0.8534, 0.2971],
         [0.5901, 0.3984, 0.3263, 0.7335, 0.5620],
         [0.6363, 0.3893, 0.2740, 0.7068, 0.1535]],

        [[0.1097, 0.2212, 0.3794, 0.8281, 0.9182],
         [0.0837, 0.3688, 0.7932, 0.7956, 0.9326],
         [0.0826, 0.4195, 0.3906, 0.1757, 0.5402],
         [0.1652, 0.6865, 0.4046, 0.0346, 0.3513]],

        [[0.4263, 0.3784, 0.6282, 0.5836, 0.5297],
         [0.1150, 0.3330, 0.9693, 0.9528, 0.1500],
         [0.0241, 0.4645, 0.0912, 0.6712, 0.9388],
         [0.5720, 0.7858, 0.2883, 0.7740, 0.6097]]])
torch.Size([3, 4, 5])


In [3]:
# Выведите его форму (shape)
print(q.shape)

torch.Size([3, 4, 5])


In [4]:
# Приведите его к форме 6 X 10
z=q.reshape(6,10)
print(z)
print(z.shape)

tensor([[0.1353, 0.1042, 0.2091, 0.9364, 0.3208, 0.1104, 0.7617, 0.8838, 0.8534,
         0.2971],
        [0.5901, 0.3984, 0.3263, 0.7335, 0.5620, 0.6363, 0.3893, 0.2740, 0.7068,
         0.1535],
        [0.1097, 0.2212, 0.3794, 0.8281, 0.9182, 0.0837, 0.3688, 0.7932, 0.7956,
         0.9326],
        [0.0826, 0.4195, 0.3906, 0.1757, 0.5402, 0.1652, 0.6865, 0.4046, 0.0346,
         0.3513],
        [0.4263, 0.3784, 0.6282, 0.5836, 0.5297, 0.1150, 0.3330, 0.9693, 0.9528,
         0.1500],
        [0.0241, 0.4645, 0.0912, 0.6712, 0.9388, 0.5720, 0.7858, 0.2883, 0.7740,
         0.6097]])
torch.Size([6, 10])


In [6]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
m1=torch.IntTensor([1,4,2,2,1])
m=z.dot(m1)

RuntimeError: ignored

In [ ]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
z1=z.mm(z.T)
print(a)
print(a.shape)
print(z1.shape)

tensor([[0.4621, 0.9101, 0.5543, 0.6047, 0.7185, 0.3547],
        [0.4986, 0.6361, 0.8602, 0.4079, 0.1214, 0.5451],
        [0.5102, 0.6807, 0.9214, 0.2685, 0.7920, 0.3614],
        [0.7973, 0.3194, 0.3710, 0.5297, 0.6693, 0.7577],
        [0.5924, 0.5125, 0.5831, 0.3053, 0.2806, 0.1933],
        [0.0440, 0.4071, 0.5060, 0.4855, 0.2950, 0.3984],
        [0.3246, 0.9462, 0.9125, 0.0677, 0.3763, 0.7837],
        [0.6485, 0.1373, 0.8892, 0.7199, 0.3432, 0.4968],
        [0.6043, 0.3646, 0.8649, 0.9491, 0.3356, 0.9373],
        [0.6566, 0.2159, 0.0248, 0.9165, 0.8477, 0.4917]])
torch.Size([10, 6])
torch.Size([6, 6])


In [ ]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x=torch.FloatTensor([1,0.5,2])
ys=3*x**2-74
print(ys)

tensor([-71.0000, -73.2500, -62.0000])


In [9]:
# Создайте единичный тензор размера 5x6
x=torch.ones(5,6)
print(x)
print(x.shape)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
torch.Size([5, 6])


In [10]:
# Переведите его в формат numpy
x.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [11]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 
for w1 in (1, 2, 3, 4):
  y = x**w1 - 2 * x**2 + 5
  print(y)


tensor([[4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.]])
tensor([[4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.]])
tensor([[4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.]])
tensor([[4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4.]])
